[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "sh -c 'npx prisma migrate deploy && node dist/src/main'"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[services]]
internalPort = 3000
